shortcut_commit_deps:
    path: /commit-deps
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md
        permanent: true

shortcut_xdebug:
    path: /xdebug
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '/doc/articles/troubleshooting.md#xdebug-impact-on-composer'
        permanent: true

shortcut_basic_usage:
    path: /basic-usage
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '/doc/01-basic-usage.md'
        permanent: true

shortcut_root:
    path: /root
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /doc/faqs/how-to-install-untrusted-packages-safely.md
        permanent: true

shortcut_repoprio:
    path: /repoprio
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /doc/articles/repository-priorities.md
        permanent: true

shortcut_dep_on_root:
    path: /dep-on-root
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /doc/articles/troubleshooting.md#dependencies-on-the-root-package
        permanent: true

shortcut_root_version:
    path: /root-version
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /doc/articles/troubleshooting.md#root-package-version-detection
        permanent: true

shortcut_ssl_local_cert:
    path: /local-issuer
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /doc/articles/troubleshooting.md#ssl-certificate-problem-unable-to-get-local-issuer-certificate
        permanent: true

shortcut_install:
    path: /install
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /doc/01-basic-usage.md#installing-dependencies
        permanent: true

shortcut_v2:
    path: /2
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: 'https://blog.packagist.com/composer-2-0-is-now-available'
        permanent: true

shortcut_allow_plugins:
    path: /allow-plugins
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /doc/06-config.md#allow-plugins
        permanent: true

shortcut_constraints:
    path: /constraints
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /doc/articles/versions.md#writing-version-constraints
        permanent: true
